from enum import StrEnum


class PlatformCode(StrEnum):
    APPLE_MUSIC = "APPLE_MUSIC"
    SPOTIFY = "SPOTIFY"
    YOUTUBE_VIDEO = "YOUTUBE_VIDEO"
    YOUTUBE_MUSIC = "YOUTUBE_MUSIC"
    AMAZON_MUSIC = "AMAZON_MUSIC"


class SourceCode(StrEnum):
    APPLE_MUSIC_API = "APPLE_MUSIC_API"
    YOUTUBE_DATA_API = "YOUTUBE_DATA_API"
    YOUTUBE_MUSIC_CHARTS = "YOUTUBE_MUSIC_CHARTS"
    SPOTIFY_CHARTS = "SPOTIFY_CHARTS"
    SPOTIFY_WEB_API = "SPOTIFY_WEB_API"
    AMAZON_MUSIC_API = "AMAZON_MUSIC_API"
    SOUNDCHARTS = "SOUNDCHARTS"
    CHARTMETRIC = "CHARTMETRIC"
    LUMINATE = "LUMINATE"
    MANUAL_AUTHORIZED_FILE = "MANUAL_AUTHORIZED_FILE"


class ChartFrequency(StrEnum):
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    OTHER = "OTHER"


class MetricType(StrEnum):
    NONE = "NONE"
    STREAMS = "STREAMS"
    VIEWS = "VIEWS"
    UNITS = "UNITS"
    CREATIONS = "CREATIONS"


class ItemKind(StrEnum):
    CATALOG_TRACK = "CATALOG_TRACK"
    VIDEO = "VIDEO"
    MUSIC_VIDEO_ROLLUP = "MUSIC_VIDEO_ROLLUP"
    OTHER = "OTHER"


class CoverageStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    MISSING = "MISSING"
    NOT_SUPPORTED = "NOT_SUPPORTED"
    NOT_LICENSED = "NOT_LICENSED"
    NOT_COLLECTED = "NOT_COLLECTED"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"


class ResolutionStatus(StrEnum):
    MATCHED_EXACT = "MATCHED_EXACT"
    MATCHED_HIGH_CONFIDENCE = "MATCHED_HIGH_CONFIDENCE"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    REJECTED = "REJECTED"
    UNRESOLVED = "UNRESOLVED"


class RightsOperation(StrEnum):
    FETCH = "FETCH"
    IMPORT = "IMPORT"
    STORE_RAW = "STORE_RAW"
    STORE_NORMALIZED = "STORE_NORMALIZED"
    ANALYZE = "ANALYZE"
    EXPORT_AGGREGATE = "EXPORT_AGGREGATE"
    REDISTRIBUTE_ROWS = "REDISTRIBUTE_ROWS"
    SHARE_WITH_COLLABORATORS = "SHARE_WITH_COLLABORATORS"


class RightsProfileStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    DENIED = "DENIED"
    EXPIRED = "EXPIRED"


class TemporalAlignmentPolicy(StrEnum):
    SAME_NATIVE_FREQUENCY = "SAME_NATIVE_FREQUENCY"
    INTERVAL_OVERLAP = "INTERVAL_OVERLAP"
